### PR TITLE
Git pr

### LINKED ISSUE #102: Github command UI refactor
image

Instead of having multiple embeds, return 1

image

Wrap command usage in \` and use the naming convention as stated [here](https://github.com/SCE-Development/SCE-discord-bot/wiki/Example-naming-convention)

### PR DESCRIPTION
**Pull request by RTX-Banana**
s!github now has page system and displays 10prs per page
resolved #102

### CODE REVIEW

**Comment by jerrylee17** [comment]
`npm run lint`

**Comment by jerrylee17** [comment]
Also rebase

**Review by jerrylee17 — APPROVED** [review]

**Review by charlotte-zhuang — COMMENTED** [review]
It would be nice to only add reactions for turning pages if there's more than one page and add the ability to go backwards from the first page to the last page.

**Comment by RTX-Banana** [comment]
ill take a look at doing that later this week or next probably

**Pull request merged**
