### PR TITLE
Added threadDelete Resolver

### PR DESCRIPTION
**Pull request by charlotte-zhuang**
Deletes a thread by theadID and all associated threadMessages.

### CODE REVIEW

**Comment by charlotte-zhuang** [comment]
I rebased with origin/master, but I'm not sure why all those other files are showing up as changed.

**Comment by jerrylee17** [comment]
1 commit behind master... Might be because your master branch is not up to date

Try this
```
git checkout master
git pull
git checkout <yourbranch>
git rebase master
```

**Comment by charlotte-zhuang** [comment]
I think everything's working now.

**Review by jerrylee17 — APPROVED** [review]
Looks good! 
Only potential bug is that threadMessages returns null. Shouldn't be a problem thought because you never use threadMessages when you delete it.
image

**Comment by jerrylee17** [comment]
@charlotte-zhuang you can merge this in

**Pull request merged**
