### PR TITLE
Fixed github command

### PR DESCRIPTION
**Pull request by jerrylee17**
#53 was incorrectly modified and raised new issues for the `github` and `event` commands. Currently working on fixing the `event` command.

It now actually communicates with core-v4 endpoints

### CODE REVIEW

**Review by qsaml — COMMENTED** [review]
event still broken in general yeah but clihelp for sure works

**Review by qsaml — APPROVED** [review]
I forgot to approve this, my bad

**Review by charlotte-zhuang — APPROVED** [review]
Looks good to me

**Comment by jerrylee17** [comment]
> event still broken in general yeah but clihelp for sure works

Event is broken on core-v4's side

**Comment by jerrylee17** [comment]
@qsaml this issue fixes `s!github`

**Pull request merged**
